name: 🐛 Bug Report
description: Report a problem or issue with the activities system
title: "[Bug]: "
labels: ["bug", "needs-investigation"]
assignees: 
  - Copilot
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        
        Use this template to report problems or issues with the Mergington High School activities system.
        
        **Important**: Please provide as much detail as possible to help the coding agent understand and fix the issue quickly.

  - type: dropdown
    id: bug_category
    attributes:
      label: Bug Category
      description: What area of the system is affected?
      options:
        - Activity Display (activities not showing correctly)
        - Student Registration (problems signing up/unregistering)
        - Teacher Authentication (login issues)
        - User Interface (visual problems, layout issues)
        - Data Persistence (information not saving)
        - API/Backend (server errors, data issues)
        - Mobile/Responsive Design (problems on mobile devices)
        - Performance (slow loading, timeouts)
        - Other (specify below)
    validations:
      required: true

  - type: input
    id: custom_bug_category
    attributes:
      label: Custom Bug Category
      description: If you selected "Other" above, please specify
      placeholder: e.g., "Email notifications"

  - type: textarea
    id: bug_summary
    attributes:
      label: Bug Summary
      description: Provide a clear, concise description of the problem
      placeholder: e.g., "Students cannot register for activities when maximum capacity is reached"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: List the exact steps to reproduce the problem
      placeholder: |
        1. Go to the activities page
        2. Click on 'Chess Club'
        3. Try to register a student
        4. Error message appears
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe what should happen instead
      placeholder: e.g., "Student should be added to the activity and confirmation message should appear"
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happens
      placeholder: e.g., "Error message shows 'Failed to register student' and student is not added to the activity"
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: How often does this happen?
      description: Select the frequency of this bug
      options:
        - Always (100% of the time)
        - Often (more than 50% of the time)
        - Sometimes (less than 50% of the time)
        - Rarely (very infrequently)
        - Only once (happened one time)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How severe is this issue?
      options:
        - Critical - System is unusable or data is lost
        - High - Major functionality is broken
        - Medium - Feature works but with significant issues
        - Low - Minor issue that doesn't affect main functionality
    validations:
      required: true

  - type: checkboxes
    id: affected_users
    attributes:
      label: Who is affected by this bug?
      description: Check all that apply
      options:
        - label: Students viewing activities
        - label: Students registering for activities
        - label: Teachers logging in
        - label: Teachers managing registrations
        - label: All users
        - label: Mobile users specifically
        - label: Desktop users specifically

  - type: input
    id: browser_info
    attributes:
      label: Browser and Version
      description: What browser are you using when this happens?
      placeholder: e.g., "Chrome 120.0", "Firefox 119", "Safari 17.1", "Mobile Safari"

  - type: input
    id: device_info
    attributes:
      label: Device Information
      description: What device are you using?
      placeholder: e.g., "Windows 11 laptop", "iPhone 15", "MacBook Pro", "Android tablet"

  - type: textarea
    id: error_messages
    attributes:
      label: Error Messages
      description: Copy any error messages you see (check browser console too)
      placeholder: Include both user-facing errors and any console errors you can find
      render: text

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information that might help diagnose the issue
      placeholder: e.g., "This started happening after a specific action", "Only happens with certain activities"

  - type: checkboxes
    id: troubleshooting_attempted
    attributes:
      label: Troubleshooting Already Attempted
      description: What have you tried to fix this issue?
      options:
        - label: Refreshed the page
        - label: Cleared browser cache
        - label: Tried a different browser
        - label: Tried on a different device
        - label: Logged out and back in
        - label: None of the above

  - type: markdown
    attributes:
      value: |
        ## Technical Investigation Guidance
        
        For the coding agent investigating this bug:
        
        ### Key Areas to Check
        
        - **Frontend Issues**: Check `src/static/app.js` for JavaScript errors
        - **Backend Issues**: Review `src/backend/routers/` for API endpoint problems
        - **Database Issues**: Examine `src/backend/database.py` for data handling problems
        - **UI Issues**: Check `src/static/styles.css` and `src/static/index.html`
        
        ### Debugging Steps
        
        1. **Reproduce the Issue**: Follow the steps provided above
        2. **Check Browser Console**: Look for JavaScript errors or failed network requests
        3. **Review Server Logs**: Check for backend errors or exceptions
        4. **Validate Data Flow**: Ensure data is properly passed between frontend and backend
        5. **Test Edge Cases**: Consider boundary conditions and error scenarios
        
        ### Common Bug Patterns
        
        - **Registration Issues**: Often related to participant limits or authentication
        - **Display Issues**: Usually CSS/JavaScript problems or data formatting
        - **API Issues**: Check for proper error handling and validation
        - **Mobile Issues**: Responsive design or touch interaction problems
        
        ### Acceptance Criteria
        
        When this bug is fixed, the following should be true:
        
        - [ ] The reported issue no longer occurs when following the reproduction steps
        - [ ] The system behaves as described in the "Expected Behavior" section
        - [ ] No new bugs are introduced by the fix
        - [ ] The fix works across the same browsers/devices where the bug occurred
        - [ ] Appropriate error handling is in place to prevent similar issues
        
        ### Testing Requirements
        
        - [ ] Verify the fix resolves the reported issue
        - [ ] Test that the fix doesn't break existing functionality
        - [ ] Test on multiple browsers if UI-related
        - [ ] Test on mobile devices if responsive design is involved
        - [ ] Add error handling to prevent similar issues in the future