blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/grueni75/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Read the development guide for setup instructions
  - name: 💬 General Discussion
    url: https://github.com/grueni75/skills-expand-your-team-with-copilot/discussions
    about: Ask questions or discuss ideas that don't fit the templates above