name: ✏️ Modify Existing Activity
description: Request changes to an existing extracurricular activity
title: "[Activity Modification]: "
labels: ["enhancement", "activity-modification"]
assignees: 
  - Copilot
body:
  - type: markdown
    attributes:
      value: |
        ## Modify Existing Activity Request
        
        Use this template to request changes to an existing extracurricular activity in the Mergington High School system.
        
        **Important**: Please specify exactly what needs to be changed to ensure the coding agent can implement your request accurately.

  - type: dropdown
    id: activity_name
    attributes:
      label: Activity to Modify
      description: Which existing activity needs to be modified?
      options:
        - Chess Club
        - Programming Class
        - Math Olympiad Team
        - Debate Team
        - Weekend Robotics Workshop
        - Soccer Team
        - Basketball Team
        - Art Club
        - Manga Maniacs
        - Other (specify in details below)
    validations:
      required: true

  - type: input
    id: custom_activity_name
    attributes:
      label: Custom Activity Name
      description: If you selected "Other" above, please specify the activity name
      placeholder: e.g., "Science Fair Preparation"

  - type: checkboxes
    id: changes_requested
    attributes:
      label: What needs to be changed?
      description: Check all that apply
      options:
        - label: Activity name
        - label: Activity description
        - label: Meeting schedule (days/times)
        - label: Maximum number of participants
        - label: Remove current participants
        - label: Add specific participants

  - type: textarea
    id: new_description
    attributes:
      label: New Description (if applicable)
      description: Provide the new description for the activity
      placeholder: Only fill this if you checked "Activity description" above

  - type: input
    id: new_name
    attributes:
      label: New Activity Name (if applicable)
      description: Provide the new name for the activity
      placeholder: Only fill this if you checked "Activity name" above

  - type: dropdown
    id: new_schedule_days
    attributes:
      label: New Meeting Days (if applicable)
      description: Select new meeting days if schedule is changing
      multiple: true
      options:
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
        - Saturday
        - Sunday

  - type: input
    id: new_start_time
    attributes:
      label: New Start Time (if applicable)
      description: New start time in 24-hour format HH:MM
      placeholder: e.g., "15:30" for 3:30 PM

  - type: input
    id: new_end_time
    attributes:
      label: New End Time (if applicable)
      description: New end time in 24-hour format HH:MM
      placeholder: e.g., "17:00" for 5:00 PM

  - type: input
    id: new_max_participants
    attributes:
      label: New Maximum Participants (if applicable)
      description: New maximum number of participants
      placeholder: e.g., "20"

  - type: textarea
    id: participants_to_remove
    attributes:
      label: Participants to Remove (if applicable)
      description: List email addresses of students to remove, one per line
      placeholder: |
        student1@mergington.edu
        student2@mergington.edu

  - type: textarea
    id: participants_to_add
    attributes:
      label: Participants to Add (if applicable)
      description: List email addresses of students to add, one per line
      placeholder: |
        newstudent1@mergington.edu
        newstudent2@mergington.edu

  - type: textarea
    id: reason_for_change
    attributes:
      label: Reason for Change
      description: Explain why this change is needed
      placeholder: e.g., "Room availability changed", "Student interest increased", "Teacher schedule conflict"
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information that might be relevant
      placeholder: e.g., "This change should take effect next semester", "Need to notify current participants"

  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria
        
        When this issue is completed, the following should be implemented:
        
        - [ ] Specified changes have been made to the activity in the database
        - [ ] Updated activity information appears correctly on the website
        - [ ] If schedule changed, the new schedule is properly formatted and displayed
        - [ ] If participant changes were requested, they are reflected in the system
        - [ ] Activity still functions correctly with all existing features
        
        ## Implementation Hints
        
        - Activity data is stored in `src/backend/database.py` in the `initial_activities` dictionary
        - When changing schedule, update both the `schedule` string and `schedule_details` object
        - Participant changes should modify the `participants` array
        - If max_participants is reduced, ensure it doesn't go below current participant count
        - Test the activity thoroughly after changes
        
        ## Technical Context
        
        - Activities are initialized from `initial_activities` when database is empty
        - For persistent changes, you may need to update the database directly via the API
        - Schedule format: "Weekdays, HH:MM AM/PM - HH:MM AM/PM" for display
        - Schedule details format: {"days": ["Day1", "Day2"], "start_time": "HH:MM", "end_time": "HH:MM"}
        - Email format for participants: "name@mergington.edu"